# This is a basic workflow to help you get started with Actions

name: Integration Tests

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
    grobid:
        name: Grobid
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: lfoppiano/grobid:0.7.2
                options: -p 8070:8070
                run: |
                    cd /opt/grobid
                    EXPORT PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
                    EXPORT JAVA_HOME=/usr/local/openjdk-11
                    EXPORT LANG=C.UTF-8
                    EXPORT JAVA_VERSION=11.0.16
                    EXPORT TINI_VERSION=v0.18.0
                    /tini -s -- ./grobid-service/bin/grobid-service
    pdfanalyzer:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - run: pip install --upgrade pip && pip install -r requirements.txt
        - name: run tests
          run: python -m unittest test.test_analyzer
